# Generated by Django 4.2.5 on 2024-05-12 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("modified_time", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.file",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Segment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seg_type", models.CharField(max_length=10)),
                ("order", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="signature",
            field=models.CharField(default="这个人很懒，什么都没有留下", max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.CreateModel(
            name="AudioSegment",
            fields=[
                (
                    "segment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="user.segment",
                    ),
                ),
                ("audio", models.FileField(upload_to="audio/")),
            ],
            bases=("user.segment",),
        ),
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "file_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="user.file",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
            ],
            bases=("user.file",),
        ),
        migrations.CreateModel(
            name="ImageSegment",
            fields=[
                (
                    "segment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="user.segment",
                    ),
                ),
                ("image", models.ImageField(upload_to="image/")),
            ],
            bases=("user.segment",),
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "file_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="user.file",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("word_count", models.IntegerField(default=0)),
            ],
            bases=("user.file",),
        ),
        migrations.CreateModel(
            name="TextSegment",
            fields=[
                (
                    "segment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="user.segment",
                    ),
                ),
                ("text", models.TextField()),
            ],
            bases=("user.segment",),
        ),
        migrations.AddField(
            model_name="file",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.user"
            ),
        ),
        migrations.AddField(
            model_name="segment",
            name="note",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.note"
            ),
        ),
    ]
