# Generated by Django 4.2.5 on 2024-05-26 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='current_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='note',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.folder'),
        ),
    ]
