# Generated by Django 4.2.5 on 2024-05-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_note_current_index_alter_note_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesegment',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
